In [2]:
import numpy
from matplotlib import pyplot

In [3]:
myarray=numpy.linspace(0,5,10)
print (myarray)

[ 0.          0.55555556  1.11111111  1.66666667  2.22222222  2.77777778
  3.33333333  3.88888889  4.44444444  5.        ]


In [6]:
a=5
b='five'
c=5.0

In [7]:
type(b)

str

In [8]:
14/a

2.8

In [9]:
14/c

2.8

In [10]:
for i in range(3):
    for j in range(3):
        print(i,j)
    print("This statement is within the i-loop,but not the j-loop")

0 0
0 1
0 2
This statement is within the i-loop,but not the j-loop
1 0
1 1
1 2
This statement is within the i-loop,but not the j-loop
2 0
2 1
2 2
This statement is within the i-loop,but not the j-loop


In [11]:
for i in range(5):
    print("Hi\n")

Hi

Hi

Hi

Hi

Hi



In [13]:
myvals=numpy.array([1,2,3,4,5])
myvals

array([1, 2, 3, 4, 5])

In [14]:
myvals[0],myvals[4]

(1, 5)

In [15]:
myvals[0:3]

array([1, 2, 3])

In [16]:
a=numpy.linspace(1,5,5)

In [17]:
a

array([ 1.,  2.,  3.,  4.,  5.])

In [18]:
b=a

In [19]:
b

array([ 1.,  2.,  3.,  4.,  5.])

In [20]:
a[2]=17

In [21]:
a

array([  1.,   2.,  17.,   4.,   5.])

In [22]:
b

array([  1.,   2.,  17.,   4.,   5.])

In [23]:
c=a.copy()

In [24]:
a[2]=3

In [25]:
a

array([ 1.,  2.,  3.,  4.,  5.])

In [26]:
c

array([  1.,   2.,  17.,   4.,   5.])